Purchasable
develhope/Java23-Team2-Warehouse pull request #20
Opened 2024-03-19 21:28 UTC by OigreSergio

Ho implementato un calcolo della media per singolo prodotto , manca un test e qualche miglioria che forse può essere apportata . Fatemi sapere se qualcosa non vi torna .

2024-03-20 12:48 UTC, Calyen93 reviewed
Come mai hai scelto di lavorare su List se tutto il codice lavora con HashMap?

2024-03-21 09:55 UTC, emmathebear requested changes
Refactoring in base a quello che si è discusso.

2024-03-21 09:55 UTC, emmathebear commented on src/classes/Warehouse.java
> +    public static <Device extends Purchasable> double puchasbleMediumCost(List<Device> devices) {
Typo

2024-03-26 13:08 UTC, Calyen93 approved these changes
TEstiamolo

2024-03-27 09:54 UTC, closed without merging