Un metodo di aggiunta di un elemento al carrello attraverso l’id
develhope/Java23-Team2-Warehouse pull request #26
Opened 2024-03-21 12:11 UTC by Calyen93

Un metodo di aggiunta di un elemento al carrello attraverso l’id con relativo aggiornamento del magazzino che restituirà il carrello aggiornato.

2024-03-21 16:20 UTC, OigreSergio approved these changes

2024-03-26 10:18 UTC, emmathebear requested changes

2024-03-26 10:18 UTC, emmathebear commented on src/classes/Cart.java
> +        if (productToAdd == null) {
Da riga 97 fino a 103 può essere eliminato e qui usato il metodo di java Map `.containsKey()`

2024-03-26 10:18 UTC, emmathebear commented on src/classes/Cart.java
> +        int availableQuantity = warehouse.checkStock(productToAdd);
Questo e ridondante, perché il check sulla presenza del prodotto l'abbiamo già fatto e gestito prima. Seguendo la logica precedente qui possiamo direttamente fare un check sulla quantità nell if a riga 113:
`if (warehouse.get(productToAdd) < quantity) { `

Se invece vogliamo usare `.getOrDefault() `invochiamolo una volta all'inizio e gestiamo la risposta per le varie casistiche:
   1. Se 0 o inferiore alla quantità non aggiungiamo,
   2. Se >= aggiungiamo

2024-03-26 12:34 UTC, closed without merging