rimozione di un elemento dal carrello aggiorna magazzino
develhope/Java23-Team2-Warehouse pull request #28
Opened 2024-03-21 18:46 UTC by Calyen93

Un metodo di rimozione di un elemento dal carrello attraverso l’id con relativo aggiornamento del magazzino che restituirà il carrello aggiornato.

2024-03-22 09:56 UTC, alegudev39 approved these changes
approved

2024-03-26 10:24 UTC, emmathebear requested changes

2024-03-26 10:24 UTC, emmathebear commented on src/classes/Cart.java
> +        for (Product product : products.keySet()) {
Conviene usare `containsKey()` se c'è si rimuove altrimenti si restituisce l'errore.

2024-03-26 12:10 UTC, Calyen93 reviewed
Aggiornato con containsKey

2024-03-26 12:53 UTC, emmathebear approved these changes

2024-03-26 12:57 UTC, merged