branch purchasablePrice update no conflict anymore
develhope/Java23-Team2-Warehouse pull request #37
Opened 2024-03-27 19:02 UTC by OigreSergio

I take the last version of code and I made my modify there , I don't understand why it dont make me attach on my last branch . Im going to close the last one just to not bring confusion

2024-04-01 10:19 UTC, emmathebear requested changes
Tutto quanto mi sembra a posto cambierei solo il nome come ho detto nel commento

2024-04-01 10:19 UTC, emmathebear commented on src/warehouse/Warehouse.java
> +    public BigDecimal purchasablePrice(KindOfProduct products) {
il nome del metodo non è chiaro su cosa faccia. `averagePurchasablePrice` sarebbe meglio

2024-04-02 08:50 UTC, emmathebear approved these changes

2024-04-03 08:36 UTC, Calyen93 approved these changes

2024-04-03 08:37 UTC, merged