Scritto un nuovo metodo di ricerca che funziona tramite filtri
develhope/Java23-Team2-Warehouse pull request #38
Opened 2024-04-01 11:15 UTC by emmathebear

2024-04-02 11:23 UTC, Calyen93 approved these changes

2024-04-03 14:53 UTC, aegroto requested changes
La classe Filter va divisa in varie classi, una per ogni tipo di filtro specifico con un'interfaccia comune. Ispirato al codice scritto dall'altro team per adattare il tuo.

2024-04-03 14:53 UTC, aegroto commented on Java-Master-Calculator.iml
> +      <library name="testng">
TestNG non la utilizzate, questa dipendenza non dovrebbe esserci. Ricontrolla tutte le modifiche fatte a questo file

2024-04-03 14:53 UTC, aegroto commented on Java-Master-Calculator.iml
> +      <library name="JUnit4">
Se usi JUnit 5.8.1, questa dipendenza a JUnit 4 non serve

2024-04-03 14:53 UTC, aegroto commented on src/product/Product.java
> +    private Integer id;
Perchè cambiare int ad Integer qui?

2024-04-03 14:53 UTC, aegroto commented on src/product/Product.java
> +    public KindOfProduct getArticle() {
questo getter andrebbe chiamato getKindOfProduct a questo punto

2024-04-03 14:53 UTC, aegroto commented on src/product/Product.java
> +    public Double getDisplay() {
Perchè non utilizzare il tipo primitivo double in questo caso?

2024-04-03 14:53 UTC, aegroto commented on src/search/Filter.java
> +public class Filter {
Andrebbero fatte classi diverse per ogni tipo di filtro, non un'unica classe. Serve un'interfaccia comune ProductFilter. Puoi ispirarti alla struttura implementata dall'altro team.

2024-04-03 14:53 UTC, aegroto commented on src/search/FilterBuilder.java
> +public class FilterBuilder {
Ci potrebbe stare nel FilterBuilder considerare tutti i tipi di filtri. Tuttavia, questa implementazione è poco scalabile poiché se si vogliono aggiungere filtri per ulteriori tipi bisogna modificare tutte le classi, che diventano via via più grandi.

2024-04-03 14:53 UTC, aegroto commented on src/search/Search.java
> +    private void filterResults(Predicate<Product> predicate) {
Buona l'implementazione con lo stream programming, però va rivista perché la classe in se diventa troppo complessa se utilizza un'unica classe Filter

2024-04-03 14:53 UTC, aegroto commented on src/test/SearchTest.java
> +public class SearchTest {
Vanno aggiunti altri tipi di test. Qui l'unica cosa che viene verificata è che il numero di risultati sia quello che ci si aspetta, ma non si verifica mai il contenuto.

2024-04-09 08:55 UTC, Calyen93 approved these changes

2024-04-09 12:27 UTC, emmathebear commented on src/main/java/console/ConsoleSearch.java
Codice relativo al vecchio metodo di ricerca, al momento commentato perché è da rivedere la logica in vista di un nuovo sistema console

2024-04-10 14:43 UTC, aegroto approved these changes

2024-04-10 14:43 UTC, merged