TEST Remove Product
develhope/Java23-Team2-Warehouse pull request #41
Opened 2024-04-02 23:47 UTC by OigreSergio

Test to remove product from WareHouse

2024-04-03 08:35 UTC, Calyen93 approved these changes

2024-04-04 14:12 UTC, ilGrandeWorro requested changes

2024-04-04 14:12 UTC, ilGrandeWorro commented on src/Testers/WarehouseTest.java
> +        fillUpWarehouse(warehouse);
a questo punto non credo serva fillUpWarehouse

2024-04-04 14:12 UTC, ilGrandeWorro commented on src/Testers/WarehouseTest.java
> +       assertEquals(initialQuantity - quantityToRemove , warehouse.getStock().get(test1).intValue());
initialQuantity - quantityToRemove-> 1

Non vedo perché mettere la sottrazione delle variabili in questo caso, visto che sono state inizializzate nel metodo, non possono che risultare 1. Sarebbe stato diverso se i valori fossero stati presi nella definizione del metodo

2024-04-06 21:51 UTC, closed without merging