Refactoring Package
develhope/Java23-Team2-Warehouse pull request #49
Opened 2024-04-10 15:08 UTC by Calyen93

Refactoring Package

2024-04-12 00:06 UTC, ilGrandeWorro requested changes
la test class di search non ha un package apposito, rivedere la classe main

2024-04-12 00:06 UTC, ilGrandeWorro commented on src/main/java/Main.java
> +package main.java;
Credo che anche questo sia da correggere

2024-04-12 00:06 UTC, ilGrandeWorro commented on src/test/java/SearchTest.java
> -package test;
Qui dice che è fuori dal package test, creare un package search in test in cui mettere questa classe

2024-04-14 14:31 UTC, ilGrandeWorro approved these changes

2024-04-16 08:37 UTC, OigreSergio approved these changes

2024-04-16 08:37 UTC, merged